---
title: "Covid_Infection_Modeling_R"
author: "Mitchell Nelson"
date: "2023-08-10"
output: html_document
---

## Packages

```{r}
library(tidyverse)
library(ggplot2)
library(faraway)
library(leaps)
library(car)
library(nlme)
library(corrplot)
```


## Brief Data Cleaning and Updating with More Currents Values (according to the time of this project's completion)

```{r}
covid <- read.csv("COVID19_state.csv", sep = ",")

#Removed date of school closure
covid <- covid[, -26]

#Removed DC
covid <- covid[-8, ]

#Updating counts
DeathsCurr <- c(1209, 19541, 11366, 29852, 89947, 12273,10826, 2896, 73789, 36217, 1404, 9510, 4921, 37849, 23535,8524, 15322, 17220, 20219, 14422, 2280, 35935, 12752, 20192, 12423, 3262, 23373, 2304, 4195, 2472, 33371, 7438, 10684, 67548, 38360, 14219, 7478, 44578, 3532, 17734, 2901, 25846, 88146, 4740, 20124, 629, 12703, 14402, 6823, 1807)

InfCurr <- c(250000,1300000, 835000, 2000000, 9180000, 1380000, 751000, 261000, 5900000,  2440000, 239000, 761000, 445000,3120000,1700000, 773000, 1330000, 1240000, 1740000,1030000,  242000, 2410000, 1440000, 1430000, 797000, 274000, 2650000, 241000, 497000,307000 , 2240000, 521000, 717000, 5090000, 2690000, 1040000, 714000, 2800000,368000, 1470000, 238000 , 1980000,6730000, 931000,  1690000,122000, 1480000, 1600000 , 500000, 156000  )

covid["DeathsCurr"] <- DeathsCurr
covid["InfCurr"] <- InfCurr

#Removing old counts
covid <- covid[, -2]
covid <- covid[, -2]
covid <- covid[, -2]


covid

```
## Creating percentages for deaths and infections

```{r}
DeathInf <- c()
InfPop <- c()
DeathPop = c()

for(i in 1:50)
{
InfPop[i] <- covid$InfCurr[i]/covid$Population[i] *100
DeathInf[i] <- covid$DeathsCurr[i]/ covid$InfCurr[i] *100
DeathPop[i] <- covid$DeathsCurr[i]/covid$Population[i] *100
}

covid["InfPop"] <- InfPop
covid["DeathInf"] <- DeathInf
covid["DeathPop"] <- DeathPop

covid

```

## Exploratory Data Analysis and Data Visualizations

```{r}
summary(covid)

```


```{r}
covidcor <- covid[,-1]
full_covid_cor <- cor(covidcor)
corrplot(full_covid_cor, tl.col = "black", tl.cex = .75, order = "hclust")



covid_cor_test <- cor.mtest(covidcor, conf.level = 0.95)
corrplot(full_covid_cor, p.mat = covid_cor_test$p, method = 'circle', insig='blank',
          number.cex = 0.5, tl.col = "black", tl.cex = .75, order = "hclust")


DeathsCurr_cor <- as.data.frame(cor(covidcor[,colnames(covidcor) != "DeathsCurr"], covidcor$DeathsCurr))
InfCurr_cor <- as.data.frame(cor(covidcor[,colnames(covidcor) != "InfCurr"], covidcor$InfCurr))

DeathsCurr_cor
InfCurr_cor

subset(DeathsCurr_cor, abs(V1) > 0.3)
subset(InfCurr_cor, abs(V1) > 0.3)
```

```{r}
Pop.D.Quart <- ntile(covid$Pop.Density, 4)
covid.plot <- covid
covid.plot["Pop.D.Quart"] <- Pop.D.Quart

outliers <- function(x) {
  return(x < quantile(x, .25) - 1.5*IQR(x) | x > quantile(x, .75) + 1.5*IQR(x))
}


covid.plot <- covid.plot %>%
        group_by(Pop.D.Quart) %>%
        mutate(outlierDth = ifelse(outliers(DeathsCurr), State, NA))

covid.plot <- covid.plot %>%
        group_by(Pop.D.Quart) %>%
        mutate(outlierInf = ifelse(outliers(InfCurr), State, NA))


ggplot(data = covid.plot, aes(y = DeathsCurr, x = Pop.D.Quart, group = Pop.D.Quart)) + geom_boxplot(fill = "light blue") + 
  stat_summary(fun.y = mean, color = "red")+ 
 scale_y_continuous(name = "Deaths by covid") +
 scale_x_continuous(name = "Population Density Grouped by Quartiles") +
    geom_text(aes(label=outlierDth), na.rm=TRUE, vjust=-0.6)

ggplot(data = covid.plot, aes(y = InfCurr, x = Pop.D.Quart, group = Pop.D.Quart)) + geom_boxplot(fill = "light blue") + 
  stat_summary(fun.y = mean, color = "red")+ 
 scale_y_continuous(name = "Covid Infections") +
 scale_x_continuous(name = "Population Density Grouped by Quartiles") +
  geom_text(aes(label=outlierInf), na.rm=TRUE, vjust=1.2)


```

```{r}
ggplot(data = covid, aes(x = Population, y = DeathsCurr)) + geom_point() + 
 scale_y_continuous(name = "Deaths by covid") + 
  geom_smooth(method = "lm")

ggplot(data = covid, aes(x = Population, y = InfCurr)) + geom_point() + 
 scale_y_continuous(name = "Covid Infections") + 
  geom_smooth(method = "lm")

```


```{r}
ggplot(covid, aes(x = DeathInf)) + geom_histogram(bins = 10, fill = "light blue", color = "black")  + 
 scale_y_continuous(name = "Number of States") + 
 scale_x_continuous(name = "Percentage Dead after Infected")

ggplot(covid, aes(x = DeathsCurr)) + geom_histogram(bins = 10, fill = "light blue", color = "black")   + 
 scale_y_continuous(name = "Number of States") + 
 scale_x_continuous(name = "Current Deaths from Covid")

ggplot(covid, aes(x = InfCurr)) + geom_histogram(bins = 10, fill = "light blue", color = "black")   + 
 scale_y_continuous(name = "Number of States") + 
 scale_x_continuous(name = "Current Infections from Covid")

ggplot(covid, aes(x = Pop.Density)) + geom_histogram(bins = 10, fill = "light blue", color = "black")   + 
 scale_y_continuous(name = "Number of States") + 
 scale_x_continuous(name = "Population Density")

```

## Deaths per Infection Analysis

```{r}
covid.DI <- subset(covid, select = -c(Population, Pop.Density, DeathsCurr, InfCurr, InfPop, DeathPop, State))


reg.full.DI <- regsubsets(DeathInf ~., data = covidDeathInf)
reg.full.DI.sum <- summary(reg.full.DI)

which.max(reg.full.DI.sum$adjr2)
which.min(reg.full.DI.sum$cp)
which.min(reg.full.DI.sum$bic)

plot(reg.full.DI.sum$adjr2, xlab = "Number of Predictors", ylab = "Adjusted R-Squared", type = "l")
points(8, reg.full.DI.sum$adjr2[8], col = "red", cex = 2,
pch = 20)

plot(reg.full.DI.sum$cp, xlab = "Number of Predictors", ylab = "Mallow CP", type = "l")
points(7, reg.full.DI.sum$cp[7], col = "red", cex = 2,
pch = 20)

plot(reg.full.DI.sum$bic, xlab = "Number of Predictors", ylab = "BIC", type = "l")
points(6, reg.full.DI.sum$bic[6], col = "red", cex = 2,
pch = 20)

plot(reg.full.DI, scale = "Cp")
plot(reg.full.DI, scale = "adjr2")

coef(reg.full.DI, 6)
```




```{r}
DI.best <- lm(data = covid.DI, DeathInf ~ Gini + ICU.Beds + Smoking.Rate +  Med.Large.Airports + Urban + Age.26.54)
summary(DI.best)
plot(DI.best)
```

## Infected Population Analysis
```{r}
covid.IP <- subset(covid, select = -c(Population, Pop.Density, DeathsCurr, InfCurr, DeathInf, DeathPop, State))

reg.full.IP <- regsubsets(InfPop ~., data = covid.IP)
reg.full.IP.sum <- summary(reg.full.IP)

which.max(reg.full.IP.sum$adjr2)
which.min(reg.full.IP.sum$cp)
which.min(reg.full.IP.sum$bic)

plot(reg.full.IP.sum$adjr2, xlab = "Number of Predictors", ylab = "Adjusted R-Squared", type = "l")
points(8, reg.full.IP.sum$adjr2[8], col = "red", cex = 2,
pch = 20)

plot(reg.full.IP.sum$cp, xlab = "Number of Predictors", ylab = "Mallow CP", type = "l")
points(8, reg.full.IP.sum$cp[8], col = "red", cex = 2,
pch = 20)

plot(reg.full.IP.sum$bic, xlab = "Number of Predictors", ylab = "BIC", type = "l")
points(3, reg.full.IP.sum$bic[3], col = "red", cex = 2,
pch = 20)

plot(reg.full.IP, scale = "bic")
plot(reg.full.IP, scale = "Cp")
plot(reg.full.IP, scale = "adjr2")

coef(reg.full.IP, 8)
```

```{r}
IP.best <- lm(data = covid.IP, InfPop ~ Gini + ICU.Beds + Income + Sex.Ratio + Physicians + Hospitals + Health.Spending + Age.0.25)
summary(IP.best)
plot(IP.best)
```


## Dead Population Analysis
```{r}
covid.DP <- subset(covid, select = -c(Population, Pop.Density, DeathsCurr, InfCurr, InfPop, DeathInf, State))


reg.full.DP <- regsubsets(DeathPop ~., data = covid.DP)
reg.full.DP.sum <- summary(reg.full.DP)

which.max(reg.full.DP.sum$adjr2)
which.min(reg.full.DP.sum$cp)
which.min(reg.full.DP.sum$bic)

plot(reg.full.DP.sum$adjr2, xlab = "Number of Predictors", ylab = "Adjusted R-Squared", type = "l")
points(8, reg.full.DP.sum$adjr2[8], col = "red", cex = 2,
pch = 20)

plot(reg.full.DP.sum$cp, xlab = "Number of Predictors", ylab = "Mallow CP", type = "l")
points(8, reg.full.DP.sum$cp[8], col = "red", cex = 2,
pch = 20)

plot(reg.full.DP.sum$bic, xlab = "Number of Predictors", ylab = "BIC", type = "l")
points(8, reg.full.DP.sum$bic[8], col = "red", cex = 2,
pch = 20)

plot(reg.full.DP, scale = "bic")
plot(reg.full.DP, scale = "Cp")
plot(reg.full.DP, scale = "adjr2")

coef(reg.full.DP, 8)
```

```{r}
DP.best <- lm(data = covid.DP, DeathPop ~ Gini + ICU.Beds + Sex.Ratio + Smoking.Rate + Respiratory.Deaths + Med.Large.Airports + Urban + Age.26.54)
summary(DP.best)
plot(DP.best)
```
















